---

server:
  url: http://www.domain-name.com/game/on
  content_type: Content-Type:application/json
db:
  host: 'localhost'
  username: 'root'
  password: ''
  database: 'hangman'
  encoding: 'utf8'
